pipeline {
    agent none

    stages {
        stage('Build and test') {
            agent {
                docker {
                    image 'maven:3.9.9-eclipse-temurin-17'
                    args '-v maven-repo:/home/ubuntu/.m2'
                }
            }
            steps {
                dir('alert-consumer-api') {
                    withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_API_KEY')]) {
                        sh 'mvn clean verify -Dnvd.api.key=$NVD_API_KEY'
                    }
                }
            }
            post {
                always {
                    dir('alert-consumer-api') {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }    
    }
}